# Generated by Django 3.2.9 on 2021-11-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Company_name', models.CharField(max_length=200)),
                ('Email_name', models.CharField(max_length=200)),
                ('Phone_number', models.CharField(max_length=100)),
                ('Subject_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
