# Generated by Django 3.2.9 on 2021-11-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
